name: My Daily Commit
on:
  schedule:
    - cron: "0 17 */2 * *" # Run every 2 days at 17:00 UTC (00:00 WIB Indonesia)
  workflow_dispatch:
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: docs/status-updates
      - name: Random commit 1-3 times
        run: |
          FILE="hi_there.md"
          git config --global user.name "alifsuryadi"
          git config --global user.email "alifsuryadi037@gmail.com"

          # Create file if it doesn't exist
          if [ ! -f "$FILE" ]; then
            echo "Hello, my name is Alif" > "$FILE"
            echo "commit number: 0" >> "$FILE"
          fi

          # Get current commit number
          CURRENT_COUNT=$(grep -oP 'commit number: \K\d+' "$FILE")
          if [ -z "$CURRENT_COUNT" ]; then
            CURRENT_COUNT=0
          fi

          # Random commit count between 1 and 3
          NUM_COMMITS=$(shuf -i 1-3 -n 1)
          echo "Generating $NUM_COMMITS commits..."

          for ((i = 1; i <= NUM_COMMITS; i++)); do
            CURRENT_COUNT=$((CURRENT_COUNT + 1))
            sed -i "/commit number: /c\commit number: $CURRENT_COUNT" "$FILE"
            git add "$FILE"
            git commit -m "Automated commit number $CURRENT_COUNT"
          done

          git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/alifsuryadi/alifsuryadi.git docs/status-updates
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
